//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NickAc.LightPOS.Backend.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NickAc.LightPOS.Backend.Translation.Translation-EN", typeof(Translation_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name:.
        /// </summary>
        public static string add_prod_name {
            get {
                return ResourceManager.GetString("add_prod_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price:.
        /// </summary>
        public static string add_prod_price {
            get {
                return ResourceManager.GetString("add_prod_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $prefix - Add Product.
        /// </summary>
        public static string add_prod_title {
            get {
                return ResourceManager.GetString("add_prod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string create_user_admin {
            get {
                return ResourceManager.GetString("create_user_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        public static string create_user_okbutton {
            get {
                return ResourceManager.GetString("create_user_okbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string edit_user_name {
            get {
                return ResourceManager.GetString("edit_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user.
        /// </summary>
        public static string edit_user_okbutton {
            get {
                return ResourceManager.GetString("edit_user_okbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string edit_user_password {
            get {
                return ResourceManager.GetString("edit_user_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions:.
        /// </summary>
        public static string edit_user_permissions {
            get {
                return ResourceManager.GetString("edit_user_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $prefix - User Management.
        /// </summary>
        public static string edit_user_title {
            get {
                return ResourceManager.GetString("edit_user_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string main_menu_add_user {
            get {
                return ResourceManager.GetString("main_menu_add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string main_menu_labelMain {
            get {
                return ResourceManager.GetString("main_menu_labelMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string main_menu_labelManagement {
            get {
                return ResourceManager.GetString("main_menu_labelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open $prefix.
        /// </summary>
        public static string main_menu_openLightPOSTile {
            get {
                return ResourceManager.GetString("main_menu_openLightPOSTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $prefix Management.
        /// </summary>
        public static string main_menu_pos_management {
            get {
                return ResourceManager.GetString("main_menu_pos_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $prefix - Menu.
        /// </summary>
        public static string main_menu_title {
            get {
                return ResourceManager.GetString("main_menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply discounts.
        /// </summary>
        public static string permissions_apply_discounts {
            get {
                return ResourceManager.GetString("permissions_apply_discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create users.
        /// </summary>
        public static string permissions_create_user {
            get {
                return ResourceManager.GetString("permissions_create_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do sales.
        /// </summary>
        public static string permissions_do_sale {
            get {
                return ResourceManager.GetString("permissions_do_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print receipts.
        /// </summary>
        public static string permissions_print_receipt {
            get {
                return ResourceManager.GetString("permissions_print_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove users.
        /// </summary>
        public static string permissions_remove_user {
            get {
                return ResourceManager.GetString("permissions_remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightPOS.
        /// </summary>
        public static string prefix {
            get {
                return ResourceManager.GetString("prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string user_login_loading {
            get {
                return ResourceManager.GetString("user_login_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string user_login_okbutton {
            get {
                return ResourceManager.GetString("user_login_okbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string user_login_simple_title {
            get {
                return ResourceManager.GetString("user_login_simple_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $prefix - $user_login_simple_title.
        /// </summary>
        public static string user_login_title {
            get {
                return ResourceManager.GetString("user_login_title", resourceCulture);
            }
        }
    }
}
